# Site settings
title:          Florian Urban
description:    "Professor of Architectural History, Glasgow School of Art"
#baseurl:        "/tale"
#url:            "https://chesterhow.github.io"

remote_theme: chesterhow/tale

# Google Analytics
#google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Florian Urban
  url:          https://florianurban.com
  email:        f.urban@gsa.ac.uk

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
#  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
#paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
# disqus:         jekyll-tale

navigation:
- text: CV
  url: /cv/
- text: Publications
  url: /publications/
- text: Lectures
  url: /lectures/
- text: Contact
  url: /contact/
  layout: contact